### ISSUE TITLE
Internal use of native prettier parsers

### ISSUE THREAD

**Issue by Shinigami92** [prettier/plugin-pug#16]
Continuation of the discussion of #9

**Comment by Shinigami92** [comment]
@ikatyang 
I'm using the native parsers now more heavily: https://github.com/prettier/plugin-pug/commit/9725b196f1a82985ac78a681974ed9e3caf821b8

Now I'm currently at work and tested the commit with `yarn link`
Works nice, BUT!

### Assignments

Something like
```pug
v-list-tile.clickable(@click.native="x = true")
```
formats to
```pug
v-list-tile.clickable(@click.native="(x = true)")
```

That's interesting and I didn't expected this.
Is it expected to use this type of format?

### Class expressions

```pug
v-icon(:class="{'active': showFilterX || showFilterY }") filter_list
```
formats to
```pug
v-icon(:class="{ active: showFilterX || showFilterY }") filter_list
```

[Vue class and style: Object-Syntax](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax)
Should be fine...

### Single attributes and printWidth

I have some lines in my code that are very long and indented deeply

Options:
```json
{
   "arrowParens": "always",
   "bracketSpacing": true,
   "printWidth": 120,
   "semi": true,
   "singleQuote": true,
   "tabWidth": 3,
   "trailingComma": "none",
   "useTabs": false,
   "overrides": [
      {
         "files": ["*.pug"],
         "options": {
            "tabWidth": 3,
            "singleQuote": false
         }
      }
   ]
}
```

7 x 3 space indentation
135 cols
```pug
                     span.chart-text(v-if="profitableEntityTypeCombinations.conversions && !profitableEntityTypeCombinationsProgress")
```
formats to
```pug
                     span.chart-text(
                        v-if="profitableEntityTypeCombinations.conversions && !profitableEntityTypeCombinationsProgress"
                     )
```

I'm thinking about not to wrap if there is only one attribute 🤔

**Comment by ikatyang** [comment]
> ### Assignments
> ...
> Is it expected to use this type of format?

That's a vue event binding, which should use [`__vue_event_binding`](https://github.com/prettier/prettier/blob/8b039ae195d95a780152b21a36acbfaf2d564693/src/language-js/parser-babylon.js#L206) (see [here](https://github.com/prettier/prettier/blob/8b039ae195d95a780152b21a36acbfaf2d564693/src/language-html/printer-html.js#L973-L1011) for more info). You can compare the result from [the Prettier playground with `vue` parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoBuAtDgJYDOMNM9OcZY+jjAvMXAMwAazwAjDoLIABbvVEA6KAXpU4AkAA8yfMjABOAVziDCqAPS0GzVuzgkolzLgIOQAGhAQsbaI2RQPAMDCAB3AAVghACUPCoIegATTxBxAzxROBgAZSxM+igAc2RDEy8ACxgMHAB1Cvp4RnywOByYxrVGgE9kcF5UwsY4AxgIjKKMPGQAMzwcYa8AK0YtACEMrNy8DDgAGUK4WfnFkBWtHMKijgBFIwh4Y4W4L3yDYYM+qhNUrANCmC1ZIwCrIAAsAAZXqFhrUMlg+n84B91KkAI73eDjHyxEB4Rg0KBwOBJEmpAxwDH0CnjPCTaZIObPLzDDD0UrGF4gRhXW6Yo6Mk5cmASIFJEHIABMXkMeHYVwAwhAMFM+lBoEcvEZhgAVCSxJnDAC+RqAA) with yours, it should be the expected behavior if the both of the results are the same.

> ### Single attributes and printWidth
> ...
> I'm thinking about not to wrap if there is only one attribute 🤔

FYI, if you force single attributes not to break, you'll probably face something like this:

```pug
span.chart-text(v-if="profitableEntityTypeCombinations.conversions &&
  !profitableEntityTypeCombinationsProgress")
```

which does not look good and it's inconsistent with [Prettier JSX and HTML/Vue/Angular](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgDwDpQA8WADgIZQAEOAvMCQE4QBmAljGQEYA2cAorHYBPACpCScAMIQAtp1ZQyMVtCwA6SFABucBlhVQslAGTHKAQkYt2XXgOUxR4qbPmLlqgApMA5gzhYWAC+AHyEAPSkFCEE6KgEsehaAK5wBITwMiTcSnAxVJTE5FRaALSszDR4IFZsHDz8go5iEtJyCkoG6po6el0mZpZMdbaNDk6trh0eht4QfgFY1WGRxfkRmdm5+XEEIAA0IBAkM1jIoGQMTADunpcIZyhkWhCsACYHIJwMZGAA1nAYABlchgBQ+ZAwBipQ4ACxgMm4AHVYewAqC4ECHuxWFphMhwIFPgosLoYN4yD4ZGRkMwyNxSYdsDgAEI-f6AoFkGRwAAyCjgtPpjJAzKB4N4AEVkhB4EKGXBDuQ9LoCdSGH83hBrlBPowFDAke8YLDkABGJVMUlIn4kAmMAK6HSfACOMvgcxIjxAZCwpSgcDgbyDn38btY-gpVJpSDpCsOpJkrEh0MVIH0UB8UvdgtjwrT9SNbxNyAATIcoWRWNxwW1qQSoNBBYdkqSRFxHnHSUEgkA).

**Comment by Shinigami92** [comment]
### Single attributes and printWidth

```pug
span.chart-text(v-if="profitableEntityTypeCombinations.conversions &&
  !profitableEntityTypeCombinationsProgress")
```

This is invalid pug code and can't happen

Since pug is based heavily on indentations and the result can easily break,
I use a `printWidth` of 9000 in interpolations only for the sake of simplicity and as a compromise.

### Assignments

Ok tested it in the playground with
```html
<template>
  <v-list-tile class="clickable" @click.native="x = true"></v-list-tile>
  <v-list-tile class="clickable" @click.native="(x = true)"></v-list-tile>
  <v-list-tile class="clickable" @click.native="((x = true))"></v-list-tile>
</template>
```

and it formats always to
```
<template>
  <v-list-tile
    class="clickable"
    @click.native="x = true"
  ></v-list-tile>
  <v-list-tile
    class="clickable"
    @click.native="x = true"
  ></v-list-tile>
  <v-list-tile
    class="clickable"
    @click.native="x = true"
  ></v-list-tile>
</template>
```

without brackets.

So I will look into it and try to use `__vue_event_binding` for this. Otherwise I think I can remove to brackets on my own.

Besides, it is valid javascript binding code and a little bit like the `--arrow-parens` option.

```js
const fn = (y) => y + 42;
let x;
fn((y) => x = y);
```

is the same as
```js
const fn = (y) => y + 42;
let x;
fn((y) => (x = y));
```
_If I am not wrong?!_

**Comment by Shinigami92** [comment]
Mh... `__vue_event_binding` isn't working at all for this use-case

I think this is fine for now
I will wait on more feedback from the community
