### ISSUE TITLE
dontWrapAttributesPattern

### ISSUE THREAD

**Issue by basaran** [prettier/plugin-pug#161]
## Request / Idea

Would it make sense to have a do not wrap regex pattern, similar to `pugWrapAttributesPattern` ? Possible use cases can be to match lines with irrelevant code that doesn't require much attention or repetitive. It could save space and produce more readable code. 

For instance, if we had a `dontWrapAttributesPattern`:

```pug
v-img.shrink.mt-1.hidden-sm-and-down(
                    alt="Vuetify Name",
                    contain="",
                    min-width="100",
                    src="https://cdn.vuetifyjs.com/images/logos/vuetify-name-dark.png",
                    width="100"
                )
                
                input(name="my_name", type="text", value="my_value")
                input(name="his_name", type="text", value="my_value")
                input(name="her_name", type="text", value="my_value")
                input(name="their_name", type="text", value="my_value")
                input(name="any_name", type="text", value="my_value")
                input(name="cat_name", type="text", value="my_value")
                input(name="bird_name", type="text", value="my_value")

                my-comp(
                    :important="matter",
                    @click="anything",
                    v-slot="{ childState }"
                )
                    | {{ parentMsg }} {{ childState }}```
```

vs

```pug
                v-img.shrink.mt-1.hidden-sm-and-down(
                    alt="Vuetify Name",
                    contain="",
                    min-width="100",
                    src="https://cdn.vuetifyjs.com/images/logos/vuetify-name-dark.png",
                    width="100"
                )

                input(
                    name="my_name",
                    type="text",
                    value="my_value"
                )
                input(
                    name="his_name",
                    type="text",
                    value="my_value"
                )
                input(
                    name="her_name",
                    type="text",
                    value="my_value"
                )
                input(
                    name="their_name",
                    type="text",
                    value="my_value"
                )
                input(
                    name="any_name",
                    type="text",
                    value="my_value"
                )
                input(
                    name="cat_name",
                    type="text",
                    value="my_value"
                )
                input(
                    name="bird_name",
                    type="text",
                    value="my_value"
                )

                my-comp(
                    :important="matter",
                    @click="anything",
                    v-slot="{ childState }"
                )
                    | {{ parentMsg }} {{ childState }}

        v-spacer
```
Also both `dontWrapAttributesPattern` and `wrapAttributesPattern` should take in an object of regexs, so this can be customized with other options relating to the regex matching (i.e `ignorePugWidth` with certain rules)

**Comment by Shinigami92** [comment]
So at first I will try to answer your second part: "should take in an object of regexs"
Why should they do this? What is currently not possible? Regex is a really strong language and you can pass multiple patterns at once. IMO you also don't need any kind of order here like in e.g. `pugSortAttributesBeginning`.

So what should `dontWrapAttributesPattern` even do? Could you please add an example of how you would configure it in your prettier config?

Could you also provide a real world example? I don't like to just implement a feature because it would be nice.
Every if-else and every more complex token processing adds time on top of the whole formatting process and therefore decreases the developer experience for every of my plugin users.

In your example I would remove the `type="text"` from every input, because it's the default :thinking: 
Ok so let's say they are `type="number"`, but even then if you have a so deep indentation you could outsource this part into e.g. another vue component or try to benefit from `v-for` :thinking: 
Also the `pugPrintWidth` option helps to prevent scrolling in the x-axis of your IDE

**Comment by basaran** [comment]
Hello, I completely agree, stuff shouldn't be added because "it's nice to have". That's why I asked if it would make sense.

This is how I thought of it initially:

`pugDontWrapAttributesPattern` will bypass all wrapping altogether, no matter what the `pugPrintWidth` is set to.

But if an object of arrays are used for `pugWrapAttributesPattern`, a similar outcome could be had. For instance:

```javascript
pugWrapAttributesThreshold: 3, // default threshold
pugWrapAttributesPattern: [
     {regex: "^input.class-a", threshold: 4},
     {regex: "^input.class-b", threshold: 2},
     {regex: "^v-data", threshold: 99},
]
```

```pug
// will not be wrapped   
    input.class-a(name="my_name", type="text", value="my_value")

// will be wrapped
    input.class-b(name="his_name", type="text", value="my_value" @click="important_function")

// will be wrapped
    my-comp(:important="matter", @click="anything", v-slot="{ childState }")

// will not be wrapped
   v-data-table(:headers="headers" :items="desserts" item-key="name" class="elevation-1" :search="search" :custom-filter="filterOnlyCapsText")
  
```

The plugin is already working great and I don't think this is priority but it might be helpful in the long run. Sincerely, Thank you again for your time.

**Comment by Shinigami92** [comment]
One problem is that I need to relay on prettier and prettier doesn't support object arrays as properties
That's because it has to be CLI compatible

I'm happy for any proposals and also thanksfully for my community like you are a member of it :slightly_smiling_face: 
But in the current state of this proposal it's too complex and of too little use
