### ISSUE TITLE
Bug: Sorting isn't working as expected

### ISSUE THREAD

**Issue by SkyaTura** [prettier/plugin-pug#192]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.13.5                  |
| Prettier  | v2.2.1                  |
| Framework | vue |
| Node      | v14.15.4                  |
| OS        | mac           |

## Prettier config

```javascript
{
    pugSortAttributesBeginning: [
        '^v-else$',
        '^v-if$',
        '^v-else-if$',
        '^v-model',
        '^v-',
        '^v-for$', //v-for should be the last attribute which starts with v-
        '^:key$', // key binding should always follow v-for
        '^@',
        '^:', //any shortcut for v-bind
        '^ref$'
    ],
    pugSortAttributes: 'asc'
}
```

## Input

```vue
<template lang="pug">
div(
  v-for=""
  v-if=""
  @click=""
  :key=""
  :foo="")
</template>
```

## Output or Error

```vue
<template lang="pug">
div(
  v-if=""
  v-for=""
  @click=""
  :foo=""
  :key="")
</template>
```

## Expected Output

```vue
<template lang="pug">
div(
  v-if=""
  v-for=""
  :key=""
  @click=""
  :foo="")
</template>
```

## Additional Context

Discussion #190

**Comment by Shinigami92** [comment]
@kaangokdemir due to technical limitations the beginning patterns are taken in reverse order.
So your `^:` is seen before `^:key$` and `^:key$` is therefore never seen.

You need to modify your pattern with a negative lookahead to `^:(?!key)` and that will fix your problem.

See this for an example: https://github.com/prettier/plugin-pug/pull/210/files#diff-42e7d9c4c1a49d17a45b508ee351796aa2698bc824b499dd080276583192aad0R22-R24
