### ISSUE TITLE
Bug: Added semicolon in front of template string

### ISSUE THREAD

**Issue by lehni** [prettier/plugin-pug#206]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.14.0                  |
| Prettier  | v2.2.1                  |
| Framework | vue |
| Node      | v14.15.4                  |
| OS        | mac           |

## Prettier config

```json
{
  "printWidth": 80,
  "semi": false,
  "singleQuote": true,
  "arrowParens": "avoid",
  "trailingComma": "none",
  "pugSingleQuote": false,
  "pugAttributeSeparator": "none",
  "pugCommentPreserveSpaces": "trim-all",
  "pugWrapAttributesThreshold": 1,
  "pugWrapAttributesPattern": "^(@|v-)"
}
```

## Input

```vue
<template lang="pug">
span
  | {{ `USD ${getPrice(shopItem)}` }}
</template>
```
-->

## Output or Error

A semicolon is added in front of the template string.

```bash
span
  | {{ ;`USD ${getPrice(shopItem)}` }}
```

## Expected Output

```pug
span
  | {{ `USD ${getPrice(shopItem)}` }}
```

**Comment by Shinigami92** [comment]
This bug was introduced somewhere in https://github.com/prettier/plugin-pug/compare/1.13.5...1.14.0
I think via https://github.com/prettier/plugin-pug/commit/2e77531561aca829ff9bc21f82ec63c2a1d2bc10

@SkyaTura Do you want to have a look? Or should I fix it?
A special test for this would be nice :slightly_smiling_face:

**Comment by lehni** [comment]
I'm aware that this is the better way to write this, but the above is still strange, and `v1.13.5` wasn't doing this:

```pug
span
  | USD {{ getPrice(shopItem) }}
  ```
