### ISSUE TITLE
Comment blocks breaking tab index

### ISSUE THREAD

**Issue by ekfuhrmann** [prettier/plugin-pug#47]
When trying to comment out tab indexed pug code, prettier seems to be stripping out the tab index, rendering the code useless upon uncommenting.

I put together 2 quick example showing the issue I'm getting for both pug block comments, as well as individual line comments

**Block Comment**
![block-comment](https://user-images.githubusercontent.com/8878152/70184753-7ae66580-16b6-11ea-833b-5f10bf0978e0.gif)

And similarly, if I comment out each line, I lose my tab index...

**Line Comment**
![line-comment](https://user-images.githubusercontent.com/8878152/70184796-92255300-16b6-11ea-80a3-da8409b186b8.gif)

I'm running prettier via VScode and have it format my file on-save. My `.prettierrc` file can be found below:

```json
{
  "tabWidth": 2,
  "singleQuote": true,
  "jsxBracketSameLine": true,
  "jsxSingleQuote": true,
  "htmlWhitespaceSensitivity": "css",
  "overrides": [
    {
      "files": "*.pug",
      "options": {
        "singleQuote": true,
        "printWidth": 120,
        "attributeSeparator": "as-needed"
      }
    }
  ]
}
```

and my `.pug-lintrc` file, which even when empty still has this issue, is here:

```json
{
  "disallowBlockExpansion": true,
  "disallowClassAttributeWithStaticValue": true,
  "disallowClassLiteralsBeforeAttributes": null,
  "disallowClassLiteralsBeforeIdLiterals": true,
  "disallowClassLiterals": null,
  "disallowDuplicateAttributes": true,
  "disallowHtmlText": null,
  "disallowIdAttributeWithStaticValue": true,
  "disallowIdLiteralsBeforeAttributes": null,
  "disallowLegacyMixinCall": true,
  "disallowMultipleLineBreaks": true,
  "disallowSpaceAfterCodeOperator": null,
  "disallowSpacesInsideAttributeBrackets": null,
  "disallowSpecificAttributes": null,
  "disallowSpecificTags": null,
  "disallowStringConcatenation": true,
  "disallowStringInterpolation": null,
  "disallowTagInterpolation": true,
  "disallowTemplateString": null,
  "maximumNumberOfLines": null,
  "requireClassLiteralsBeforeAttributes": true,
  "requireClassLiteralsBeforeIdLiterals": null,
  "requireIdLiteralsBeforeAttributes": true,
  "requireLineFeedAtFileEnd": true,
  "requireLowerCaseTags": true,
  "requireSpaceAfterCodeOperator": true,
  "requireSpacesInsideAttributeBrackets": null,
  "requireSpecificAttributes": [
    {
      "html": "lang"
    },
    {
      "form": "action"
    },
    {
      "img": "alt"
    },
    {
      "input": "type"
    },
    {
      "input[type=submit]": "value"
    }
  ],
  "requireStrictEqualityOperators": true,
  "validateAttributeQuoteMarks": "'",
  "validateDivTags": true,
  "validateExtensions": null,
  "validateIndentation": 2,
  "validateLineBreaks": "LF",
  "validateSelfClosingTags": true,
  "validateTemplateString": true
}
```

As far as I can tell, I'm not doing anything crazy so I'm not really sure what is going on. This also wasn't an issue for me prior to prettier removing the config from vscode settings. Let me know if there is anything further I could provide.

In the meantime, I have disabled prettier from handling commented out code within my pug file until this is resolved.

**Comment by Shinigami92** [comment]
### Background

The idea was to remove multiple spaces from text comments.
Maybe I should do that only for `buffer`ed comments 🤔
But ... no, I cant do that because buffered comments are displayed in HTML and unbuffered ones are not

I also cant distinguish between a code comment and simple text

```pug
//   just    some      text
```

`just` could be a tag (in example a Vue Component)

### Idea 1

Implement an option `preserveCommentSpaces` (defaults to `true`)
So, if someone wants the old behaviour, it can still be used

### Idea 2

Don't trim the leading spaces
This could also be an option like in idea-1 🤔

### Idea 3

Both: idea 1 and 2 in combination 🤔🤔 (could be overkill 😏)

### Affected code lines

https://github.com/prettier/plugin-pug/blob/fc2a31fa27b7acdd74af3a318349e9faf583c0f3/src/index.ts#L397

https://github.com/prettier/plugin-pug/blob/fc2a31fa27b7acdd74af3a318349e9faf583c0f3/src/index.ts#L427

---

So, what do you think or what would you prefer?

**Comment by Shinigami92** [comment]
I have defined an option `commentPreserveSpaces` with possible values `'keep-all' | 'keep-leading' | 'trim-all'`

**Comment by ekfuhrmann** [comment]
Perfect, this works great!

Thanks for the quick fix!
