### ISSUE TITLE
Bug: Inline styling fails

### ISSUE THREAD

**Issue by binarykitchen** [prettier/plugin-pug#500]
### Plugin Version

3.0.0

### Prettier Version

3.3.3

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

20.16.0

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Prettier config

```json
//@ts-check

/** @type {import('prettier').Config} */
const config = {
  printWidth: 90,
  plugins: [
    "prettier-plugin-curly",
    "prettier-plugin-sh",
    "prettier-plugin-packagejson",
    "prettier-plugin-nginx",
    "@prettier/plugin-pug",
    "prettier-plugin-organize-imports",
  ],
  organizeImportsSkipDestructiveCodeActions: true,
};

module.exports = config;
```

### Input

```pug
doctype strict
html(lang="en", xmlns="http://www.w3.org/1999/xhtml")
  head
    title #{ subject }
    meta(http-equiv="Content-Type", content="text/html; charset=utf-8")
    meta(name="viewport", content="width=device-width,initial-scale=1")
    meta(name="x-apple-disable-message-reformatting")
    link(
      href="http://fonts.googleapis.com/css?family=Varela+Round",
      rel="stylesheet",
      type="text/css"
    )
    style.
      #{css}
  body
    #wrapper
      #main
        block main
```

### Output or Error

```bash
> videomail.io@2.0.0 prettier
> prettier --check ./etc ./src ./test

Checking formatting...
src/server/views/email/layout.pug[PugPrinter:start-pipeless-text]: The following expression could not be formatted correctly. This is likely a syntax error or an issue caused by the missing execution context. If you think this is a bug, please open a bug issue. 
code: `#{css}` 
You used interpolated code in your pipeless script tag, so you may ignore this warning. 
Found css SyntaxError: CssSyntaxError: Unknown word (1:3)
```

### Expected Output

```pug
No error :)
```

### Additional Context

Started using your cool plugin since yesterday. All worked fine until your prettier plugin started to complain about it.

I think it's ancient code but still valid, you still can inline CSS the pug way like that:
```
    style.
      #{css}
```

Thanks for all that

**Comment by Shinigami92** [comment]
So the message is coming somewhere from here

https://github.com/prettier/plugin-pug/blob/d9a44b18a683333ea6abb518dfed9d595b3bece6/src/printer.ts#L1793-L1798

As the other message also mention, you could potentially ignore the message, as it detected "interpolated code".

Maybe there is a better syntax?

Otherwise, would you like to try to open a PR on your own?

I have not worked in depth quite a while on this plugin, as it felt finished.
But you might just need to add a `tests/issues/issue-500/issue-500.test.ts` and follow the structure of the other tests.
From there it is often very easy to debug through the code 🙂

**Comment by binarykitchen** [comment]
Ah, when you raised the syntax re interpolation I changed to
```
    style
      #{css}
```

Et voilà, removing a single dot made the difference. Works now :)
